INSERT INTO TB_ARTICLE(ARTICLE_ID,ARTICLE_CONTENT,ARTICLE_NAME,ARTICLE_TAG) VALUES(1,'博客内容','java知识总结','JAVA');
INSERT INTO TB_TAG(TAG_ID,TAG_NAME) VALUES(1,'JAVA');
INSERT INTO TB_USER(USER_ID,USER_ACCOUNT,USER_NAME,USER_PWD) VALUES(1,'root','root','zucc');